import dotenv from "dotenv";
import path from "path";
dotenv.config({ path: path.join(process.cwd(), ".env") });

export default {
  node_env: process.env.NODE_ENV,
  port: process.env.PORT || 5001,
  databaseUrl: process.env.DATABASE_URL,
  jwt_access_secret_key: process.env.JWT_SECRET_KEY,
  jwt_temp_secret_key: process.env.JWT_TEMP_KEY,
  jwt_access_expire_key: process.env.JWT_EXPRESS_KEY,
  jwt_temp_expore_key: process.env.JWT_TEMP_EXPIERS,
  jwt_refress_secret_key: process.env.JWT_REFRESH_KEY,
  jwt_refresh_expire_key: process.env.JWT_REFRESS_EXPRESS_KEY,
  frontend_url: process.env.FRONTEND_URL,
  frontend_url_prod: process.env.FRONTEND_URL_PROD,
  frb_frontend_url_prod: process.env.FRB_FRONTEND_URL_PROD,
  varsity_frontend_url_prod: process.env.VARSITY_FRONTEND_URL_PROD,
  medical_frontend_url_prod: process.env.MEDICAL_FRONTEND_URL_PROD,
  frontend_url_prod_superAdmin: process.env.FRONTEND_URL_PROD_SUPERADMIN,
  smtp_email: process.env.SMTP_EMAIL,
  smtp_password: process.env.SMTP_PASSWORD,
  sms_api_key: process.env.SMSAPIKEY,
  sms_sender_id: process.env.SENDER_ID,
  email_key_access: process.env.EMAIL_KEY,
  from_email: process.env.FROM_EMAIL,
  from_email_name: process.env.FROM_EMAIL_NAME,
  replay_email: process.env.REPLAY_TO_EMAIL,
  replay_to_name: process.env.REPLAY_TO_NAME,
  bcrypt_hash_random: process.env.BCREPT_HASH_RANDOM,
  bunny_region: process.env.BUNNY_REGION,
  region: process.env.REGION,
  base_host_name: process.env.BASE_HOSTNAME,
  bunny_storage_zone_name: process.env.BUNNY_STORAGE_ZONE_NAME,
  bunny_storage_api_key: process.env.BUNNY_STORAGE_API_KEY,
  crmApiKey: process.env.CRMAPIKEY,
  teachmint_auth_key: process.env.AUTH_KEY,
  teachmint_client_id: process.env.CLIENT_ID,
  frb_host_name: process.env.FRB_HOST_NAME,
  varsity_host_name: process.env.VARSITY_HOST_NAME,
  medical_host_name: process.env.MEDICAL_HOST_NAME,
  academic_host_name: process.env.ACADEMIC_HOST_NAME,
  frb_local_host_name: process.env.FRB_LOCAL_HOST_NAME,
  admission_host_name: process.env.ADMISSION_HOST_NAME,
  engineering_host_name: process.env.ENGINEERING_HOST_NAME,
  academic_local_host_name: process.env.ACADEMIC_LOCAL_HOST_NAME,
  redis_host: process.env.REDIS_HOST,
  redis_port: process.env.REDIS_PORT,
  redis_password: process.env.REDIS_PASSWORD,
  gemini_api_key: process.env.GEMINI_API_KEY,
  google_sheet_api_key: process.env.GOOGLE_SHEET_API_KEY,
  google_sheet_id: process.env.GOOGLE_SHEET_ID,
  answer_comment_limit: 5,
  acceptHopCount: process.env.ACCEPTHOPCOUNT,
  similarity_threshold: process.env.SIMILARITY_THRESHOLD,
  academic_frontend_url_prod: process.env.ACADEMIC_FRONTEND_URL_PROD,
  bunny_Token: process.env.BUNNY_TOKEN_KEY,
  bunny_stream_base_url: process.env.BUNNY_STREAM_BASE_URL,
  bunny_token_ttl_seconds: process.env.BUNNY_TOKEN_TTL_SECONDS,
  fcm_service_account_json: process.env.FCM_SERVICE_ACCOUNT_JSON,
  shopApiKey: process.env.SHOP_API_KEY,
  flow_base_url: process.env.FLOW_BASE_URL,
  bunny_main_api_key: process.env.BUNNY_MAIN_API_KEY,
  dollar_rate: process.env.DOLLAR_RATE,
  storage_charge_rate: process.env.STORAGE_CHARGE_RATE,
  bandwidth_charge_rate: process.env.BANDWIDTH_CHARGE_RATE,
  approval_charge_rate: process.env.APPROVAL_CHARGE_RATE,
  ga_property_id: process.env.GA_PROPERTY_ID,
  ga_client_email: process.env.GA_CLIENT_EMAIL,
  ga_private_key: process.env.GA_PRIVATE_KEY,
  afs_crm_key: process.env.AFS_CRM_KEY,
  acs_camp_key: process.env.ACS_CAMP_KEY,
  google_client_id: process.env.GOOGLE_CLIENT_ID,
  apple_client_id: process.env.APPLE_CLIENT_ID,
  bunny_s3_base_url: process.env.BUNNY_S3_STORAGE_BASE_URL,
  bunny_s3_secret_access_key: process.env.BUNNY_S3_SECRET_ACCESS_KEY,
  bunny_s3_access_key: process.env.BUNNY_S3_ACCESS_KEY_ID,
  socket_admin: process.env.SOCKET_ADMIN_USER,
  socket_admin_pass: process.env.SOCKET_ADMIN_PASSWORD_HASH,
  recorded_class_watch_enabled:
    process.env.ENABLE_RECORDED_CLASS_WATCH !== "false",
  media_auth_key: process.env.MEDIA_AUTH_KEY,
  allowed_suparAdmin_email: process.env.ALLOWED_SUPERADMIN_EMAILS,

  //grand Celebration auth
  auth_token_temp_key: process.env.AUTH_TOKEN_TEMP_KEY,
  auth_token_expire_temp: process.env.AUTH_TOKEN_EXPIRE_TEMP,

  auth_refresh_temp_key: process.env.AUTH_REFRESH_TEMP_KEY,
  auth_refresh_expire_temp: process.env.AUTH_REFRESH_EXPIRE_TEMP,

  auth_token_key: process.env.AUTH_TOKEN_KEY,
  auth_token_expire: process.env.AUTH_TOKEN_EXPIRE,

  auth_refresh_token_key: process.env.AUTH_REFRESH_TOKEN,
  auth_refresh_expire: process.env.AUTH_REFRESH_EXPIRE,
};
